### PR TITLE
r/aws_vpc_dhcp_options_association: Support `default` DHCP Options ID

### LINKED ISSUE #22716: Import of aws_vpc_dhcp_options_association fails in v3.73.0
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

aws_provider: v3.73.0
terraform: v1.1.4

### Affected Resource(s)

* aws_vpc_dhcp_options_association

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

The actual issue is while importing resources:

`terraform import module.vpc.aws_vpc_dhcp_options_association.dns_resolver <vpc-id>`

Below manifest could create the needed resources for this import.

```hcl
data "aws_region" "current" {}

resource "aws_vpc" "customer_vpc" {
  cidr_block           = "10.43.4.0/22"
  enable_dns_hostnames = true
  enable_dns_support   = true
}

resource "aws_vpc_dhcp_options" "default_dhcp_options" {
  domain_name         = format("%s%s", data.aws_region.current.name, ".compute.internal")
  domain_name_servers = ["AmazonProvidedDNS"]
}

resource "aws_vpc_dhcp_options_association" "dns_resolver" {
  vpc_id          = aws_vpc.customer_vpc.id
  dhcp_options_id = aws_vpc_dhcp_options.default_dhcp_options.id
}


```

### Expected Behavior

After executing `terraform import module.vpc.aws_vpc_dhcp_options_association.dns_resolver <vpc-id>` the resource should be imported.

### Actual Behavior

After executing `terraform import module.vpc.aws_vpc_dhcp_options_association.dns_resolver <vpc-id>` this error is received:

`Error: unexpected format for ID (default-vpc-0466d39c84de5c49b), expected DHCPOptionsID-VPCID`

Verified that it does work in v3.72.0 of the provider

### PR DESCRIPTION
**Pull request by ewbankkit**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #22716.

Prior to the fix:

```console
% make testacc TESTARGS='-run=TestAccEC2VPCDHCPOptionsAssociation_default' PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccEC2VPCDHCPOptionsAssociation_default -timeout 180m
=== RUN   TestAccEC2VPCDHCPOptionsAssociation_default
=== PAUSE TestAccEC2VPCDHCPOptionsAssociation_default
=== CONT  TestAccEC2VPCDHCPOptionsAssociation_default
    vpc_dhcp_options_association_test.go:113: Step 1/2 error: Error running apply: exit status 1
        
        Error: unexpected format for ID (default-vpc-0c3d3a2ecaff91a69), expected DHCPOptionsID-VPCID
        
          with aws_vpc_dhcp_options_association.test,
          on terraform_plugin_test.tf line 15, in resource "aws_vpc_dhcp_options_association" "test":
          15: resource "aws_vpc_dhcp_options_association" "test" {
        
    testing_new.go:70: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: unexpected format for ID (default-vpc-0c3d3a2ecaff91a69), expected DHCPOptionsID-VPCID
        
--- FAIL: TestAccEC2VPCDHCPOptionsAssociation_default (13.84s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/ec2        17.503s
FAIL
make: *** [testacc] Error 1
```

Output from acceptance testing:

```console
% make testacc TESTARGS='-run=TestAccEC2VPCDHCPOptionsAssociation_' PKG=ec2 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccEC2VPCDHCPOptionsAssociation_ -timeout 180m
=== RUN   TestAccEC2VPCDHCPOptionsAssociation_basic
=== PAUSE TestAccEC2VPCDHCPOptionsAssociation_basic
=== RUN   TestAccEC2VPCDHCPOptionsAssociation_Disappears_vpc
=== PAUSE TestAccEC2VPCDHCPOptionsAssociation_Disappears_vpc
=== RUN   TestAccEC2VPCDHCPOptionsAssociation_Disappears_dhcp
=== PAUSE TestAccEC2VPCDHCPOptionsAssociation_Disappears_dhcp
=== RUN   TestAccEC2VPCDHCPOptionsAssociation_disappears
=== PAUSE TestAccEC2VPCDHCPOptionsAssociation_disappears
=== RUN   TestAccEC2VPCDHCPOptionsAssociation_default
=== PAUSE TestAccEC2VPCDHCPOptionsAssociation_default
=== CONT  TestAccEC2VPCDHCPOptionsAssociation_basic
=== CONT  TestAccEC2VPCDHCPOptionsAssociation_disappears
=== CONT  TestAccEC2VPCDHCPOptionsAssociation_default
=== CONT  TestAccEC2VPCDHCPOptionsAssociation_Disappears_dhcp
=== CONT  TestAccEC2VPCDHCPOptionsAssociation_Disappears_vpc
--- PASS: TestAccEC2VPCDHCPOptionsAssociation_Disappears_vpc (21.84s)
--- PASS: TestAccEC2VPCDHCPOptionsAssociation_disappears (25.71s)
--- PASS: TestAccEC2VPCDHCPOptionsAssociation_Disappears_dhcp (26.49s)
--- PASS: TestAccEC2VPCDHCPOptionsAssociation_default (28.16s)
--- PASS: TestAccEC2VPCDHCPOptionsAssociation_basic (28.99s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        33.742s
```

### CODE REVIEW

**Review by anGie44 — APPROVED** [review]
LGTM 🚀 

Hmm i wonder if we should try to have more unit tests for these parse "id" type methods. we have them in some places, though doesn't necessarily guarantee we'll always catch these unique ones ahead of time
