### ISSUE TITLE
CloudFront VPC Origin (AWS TF v6.17): missing required field + unexpected error occurred while expanding configuration

### ISSUE THREAD

**Issue by kkrav3ts** [hashicorp/terraform-provider-aws#44753]
### Terraform and AWS Provider Version

```console
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v6.17.0
```

### Affected Resource(s) or Data Source(s)

* `aws_cloudfront_vpc_origin`

### Expected Behavior

Resource is created.

### Actual Behavior

Resource creation FAILS. Exactly the same config worked on `v6.15`, `v6.16` but starts to fail on `v6.17`.

### Relevant Error/Panic Output

Fails with:
```console
╷
│ Error: Incompatible Types
│ 
│   with aws_cloudfront_vpc_origin.vpco["test-origin"],
│   on main.tf line 13, in resource "aws_cloudfront_vpc_origin" "vpco":
│   13: resource "aws_cloudfront_vpc_origin" "vpco" {
│ 
│ An unexpected error occurred while expanding configuration. This is always an error in the provider. Please report the following to the provider developer:
│ 
│ Source type "github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront.originSSLProtocolsModel" does not implement attr.Value
╵
╷
│ Error: creating CloudFront VPC Origin
│ 
│   with aws_cloudfront_vpc_origin.vpco["test-origin"],
│   on main.tf line 13, in resource "aws_cloudfront_vpc_origin" "vpco":
│   13: resource "aws_cloudfront_vpc_origin" "vpco" {
│ 
│ operation error CloudFront: CreateVpcOrigin, 1 validation error(s) found.
│ - missing required field, CreateVpcOriginInput.VpcOriginEndpointConfig.
│ 
╵
```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
terraform {
  required_version = "~>1.5"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "6.17"
    }
  }
}
# VPC RESOURCES
resource "aws_vpc" "main" {
  cidr_block           = "10.0.0.0/16"
}
resource "aws_subnet" "main" {
  vpc_id                  = aws_vpc.main.id
  cidr_block              = "10.0.0.0/20"
  map_public_ip_on_launch = true
}
resource "aws_internet_gateway" "main" {
  vpc_id = aws_vpc.main.id
}
resource "aws_route_table" "main" {
  vpc_id = aws_vpc.main.id

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.main.id
  }
}
resource "aws_route_table_association" "main" {
  subnet_id      = aws_subnet.main.id
  route_table_id = aws_route_table.main.id
}

# SAMPLE ORIGIN RESOURCE (EC2 INSTANCE)
data "aws_ami" "ami" {
  most_recent = true
  owners      = ["amazon"]
  filter {
    name   = "architecture"
    values = ["arm64"]
  }
  filter {
    name   = "name"
    values = ["al2023-ami-2023*"]
  }
}
resource "aws_instance" "ec2" {
  ami                    = data.aws_ami.ami.id
  instance_type          = "t4g.nano"
  subnet_id              = aws_subnet.main.id
}

# CLOUDFRONT VPC ORIGIN RESOURCE
resource "aws_cloudfront_vpc_origin" "vpco" {
  vpc_origin_endpoint_config {
    name                   = "test-origin"
    arn                    = aws_instance.ec2.arn
    http_port              = 80
    https_port             = 443
    origin_protocol_policy = "https-only"

    origin_ssl_protocols {
      items    = ["TLSv1.2"]
      quantity = 1
    }
  }

  timeouts {
    create = "20m"
    delete = "20m"
  }
}

```
</details>

### Steps to Reproduce

1. Apply configuration.
2. See error.

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

None

### Would you like to implement a fix?

No

**Comment by kkrav3ts** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-aws/issues/44691
