### PR TITLE
[bugfix] aws_cloudfront_vpc_origin: Fix "Source type `cloudfront.originSSLProtocolsModel` does not implement attr.Value" error by implementing manual expander and flattener instead of using autoflex

### LINKED ISSUE #44691: [Bug] aws_cloudfront_vpc_origin missing required field, CreateVpcOriginInput.VpcOriginEndpointConfig.
### Terraform and AWS Provider Version

```console
v1.14.0
```

### Affected Resource(s) or Data Source(s)

resource "aws_cloudfront_vpc_origin" "nlb_test"

### Expected Behavior

terraform apply

```
resource "aws_cloudfront_vpc_origin" "nlb_test" {
  vpc_origin_endpoint_config {
    name                   = "external-private-igw-test"
    arn                    = module.alb_external_private.arn
    http_port              = 80
    https_port             = 443
    origin_protocol_policy = "https-only"
    origin_ssl_protocols {
      items    = ["TLSv1.2"]
      quantity = 1
    }
  }
  timeouts {
    create = "30m"
  }
}
```

### Actual Behavior

```console
╷
│ Error: Incompatible Types
│ 
│   with aws_cloudfront_vpc_origin.nlb_test,
│   on test-vpc-origin.tf line 1, in resource "aws_cloudfront_vpc_origin" "nlb_test":
│    1: resource "aws_cloudfront_vpc_origin" "nlb_test" {
│ 
│ An unexpected error occurred while expanding configuration. This is always
│ an error in the provider. Please report the following to the provider
│ developer:
│ 
│ Source type
│ "github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront.originSSLProtocolsModel"
│ does not implement attr.Value
╵
╷
│ Error: creating CloudFront VPC Origin
│ 
│   with aws_cloudfront_vpc_origin.nlb_test,
│   on test-vpc-origin.tf line 1, in resource "aws_cloudfront_vpc_origin" "nlb_test":
│    1: resource "aws_cloudfront_vpc_origin" "nlb_test" {
│ 
│ operation error CloudFront: CreateVpcOrigin, 1 validation error(s) found.
│ - missing required field, CreateVpcOriginInput.VpcOriginEndpointConfig.
│ 
╵
```

### Relevant Error/Panic Output

```console
╷
│ Error: Incompatible Types
│ 
│   with aws_cloudfront_vpc_origin.nlb_test,
│   on test-vpc-origin.tf line 1, in resource "aws_cloudfront_vpc_origin" "nlb_test":
│    1: resource "aws_cloudfront_vpc_origin" "nlb_test" {
│ 
│ An unexpected error occurred while expanding configuration. This is always
│ an error in the provider. Please report the following to the provider
│ developer:
│ 
│ Source type
│ "github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront.originSSLProtocolsModel"
│ does not implement attr.Value
╵
╷
│ Error: creating CloudFront VPC Origin
│ 
│   with aws_cloudfront_vpc_origin.nlb_test,
│   on test-vpc-origin.tf line 1, in resource "aws_cloudfront_vpc_origin" "nlb_test":
│    1: resource "aws_cloudfront_vpc_origin" "nlb_test" {
│ 
│ operation error CloudFront: CreateVpcOrigin, 1 validation error(s) found.
│ - missing required field, CreateVpcOriginInput.VpcOriginEndpointConfig.
│ 
╵
```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
resource "aws_cloudfront_vpc_origin" "nlb_test" {
  vpc_origin_endpoint_config {
    name                   = "external-private-igw-test"
    arn                    = module.alb_external_private.arn
    http_port              = 80
    https_port             = 443
    origin_protocol_policy = "https-only"
    origin_ssl_protocols {
      items    = ["TLSv1.2"]
      quantity = 1
    }
  }
  timeouts {
    create = "30m"
  }
}
```
</details>

### Steps to Reproduce

1. create file
2. terraform apply to create resource vpc origin

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

_No response_

### Would you like to implement a fix?

No

### LINKED ISSUE #44753: CloudFront VPC Origin (AWS TF v6.17): missing required field + unexpected error occurred while expanding configuration
### Terraform and AWS Provider Version

```console
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v6.17.0
```

### Affected Resource(s) or Data Source(s)

* `aws_cloudfront_vpc_origin`

### Expected Behavior

Resource is created.

### Actual Behavior

Resource creation FAILS. Exactly the same config worked on `v6.15`, `v6.16` but starts to fail on `v6.17`.

### Relevant Error/Panic Output

Fails with:
```console
╷
│ Error: Incompatible Types
│ 
│   with aws_cloudfront_vpc_origin.vpco["test-origin"],
│   on main.tf line 13, in resource "aws_cloudfront_vpc_origin" "vpco":
│   13: resource "aws_cloudfront_vpc_origin" "vpco" {
│ 
│ An unexpected error occurred while expanding configuration. This is always an error in the provider. Please report the following to the provider developer:
│ 
│ Source type "github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront.originSSLProtocolsModel" does not implement attr.Value
╵
╷
│ Error: creating CloudFront VPC Origin
│ 
│   with aws_cloudfront_vpc_origin.vpco["test-origin"],
│   on main.tf line 13, in resource "aws_cloudfront_vpc_origin" "vpco":
│   13: resource "aws_cloudfront_vpc_origin" "vpco" {
│ 
│ operation error CloudFront: CreateVpcOrigin, 1 validation error(s) found.
│ - missing required field, CreateVpcOriginInput.VpcOriginEndpointConfig.
│ 
╵
```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
terraform {
  required_version = "~>1.5"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "6.17"
    }
  }
}
# VPC RESOURCES
resource "aws_vpc" "main" {
  cidr_block           = "10.0.0.0/16"
}
resource "aws_subnet" "main" {
  vpc_id                  = aws_vpc.main.id
  cidr_block              = "10.0.0.0/20"
  map_public_ip_on_launch = true
}
resource "aws_internet_gateway" "main" {
  vpc_id = aws_vpc.main.id
}
resource "aws_route_table" "main" {
  vpc_id = aws_vpc.main.id

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.main.id
  }
}
resource "aws_route_table_association" "main" {
  subnet_id      = aws_subnet.main.id
  route_table_id = aws_route_table.main.id
}

# SAMPLE ORIGIN RESOURCE (EC2 INSTANCE)
data "aws_ami" "ami" {
  most_recent = true
  owners      = ["amazon"]
  filter {
    name   = "architecture"
    values = ["arm64"]
  }
  filter {
    name   = "name"
    values = ["al2023-ami-2023*"]
  }
}
resource "aws_instance" "ec2" {
  ami                    = data.aws_ami.ami.id
  instance_type          = "t4g.nano"
  subnet_id              = aws_subnet.main.id
}

# CLOUDFRONT VPC ORIGIN RESOURCE
resource "aws_cloudfront_vpc_origin" "vpco" {
  vpc_origin_endpoint_config {
    name                   = "test-origin"
    arn                    = aws_instance.ec2.arn
    http_port              = 80
    https_port             = 443
    origin_protocol_policy = "https-only"

    origin_ssl_protocols {
      items    = ["TLSv1.2"]
      quantity = 1
    }
  }

  timeouts {
    create = "20m"
    delete = "20m"
  }
}

```
</details>

### Steps to Reproduce

1. Apply configuration.
2. See error.

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

None

### Important Facts and References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by tabito-hara**
to avoid an error due to autoflex's mistreatment for origin_ssl_protocols

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description

#44691 and #44753 reported an error in the `aws_cloudfront_vpc_origin` resource:

> missing required field, CreateVpcOriginInput.VpcOriginEndpointConfig

Some reporters confirmed that this issue started occurring in v6.17.0.

In v6.17, an update for Autoflex was released:
https://github.com/hashicorp/terraform-provider-aws/pull/44655

This PR introduced XML wrapper compatibility, which specifically treats structs containing `Items` and `Quantity`.  
Since the `OriginSslProtocols` struct used by the `aws_cloudfront_vpc_origin` resource has both `Items` and `Quantity`, Autoflex unintentionally treats this struct as an XML wrapper. This is the cause of the issue.

https://github.com/hashicorp/terraform-provider-aws/blob/1ae3c0b3e9cb35ee8ae90e7f742248ed25a9867f/internal/service/cloudfront/vpc_origin.go#L420-L423

To fix this issue, this PR implements a manual expander and flattener instead of using Autoflex.

While there might be some options (e.g. fixing Autoflex etc.), I believe prioritizing a quick fix is more important at this time.
See also [my comment](https://github.com/hashicorp/terraform-provider-aws/issues/44691#issuecomment-3462211683).

### Relations

Closes #44691 
Closes #44753 

### Output from Acceptance Testing

```console
$ make testacc TESTS='TestAccCloudFrontVPCOrigin_' PKG=cloudfront 
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-aws_cloudfront_vpc_origin-fix_flex_failure 🌿...
TF_ACC=1 go1.24.8 test ./internal/service/cloudfront/... -v -count 1 -parallel 20 -run='TestAccCloudFrontVPCOrigin_'  -timeout 360m -vet=off
2025/10/30 00:39:47 Creating Terraform AWS Provider (SDKv2-style)...
2025/10/30 00:39:47 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccCloudFrontVPCOrigin_basic
=== PAUSE TestAccCloudFrontVPCOrigin_basic
=== RUN   TestAccCloudFrontVPCOrigin_disappears
=== PAUSE TestAccCloudFrontVPCOrigin_disappears
=== RUN   TestAccCloudFrontVPCOrigin_update
=== PAUSE TestAccCloudFrontVPCOrigin_update
=== RUN   TestAccCloudFrontVPCOrigin_tags
=== PAUSE TestAccCloudFrontVPCOrigin_tags
=== CONT  TestAccCloudFrontVPCOrigin_basic
=== CONT  TestAccCloudFrontVPCOrigin_update
=== CONT  TestAccCloudFrontVPCOrigin_tags
=== CONT  TestAccCloudFrontVPCOrigin_disappears
--- PASS: TestAccCloudFrontVPCOrigin_disappears (997.41s)
--- PASS: TestAccCloudFrontVPCOrigin_basic (1003.02s)
--- PASS: TestAccCloudFrontVPCOrigin_update (1021.71s)
--- PASS: TestAccCloudFrontVPCOrigin_tags (1034.54s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront 1039.440s

```
Without this modification, all tests failed.

### CODE REVIEW

**Comment by ewbankkit** [comment]
@tabito-hara Thanks for the contribution :tada: :clap:.
