### PR TITLE
bug/regression fix: 6.35 `Incompatible Types` `while flattening`

### LINKED ISSUE #46761: 6.35.0 Regression: LifecycleRuleAndOperator cannot be flattened
### Terraform and AWS Provider Version

```console
Terraform v1.14.6
on linux_amd64
+ provider registry.terraform.io/grafana/grafana v4.27.0
+ provider registry.terraform.io/hashicorp/aws v6.35.0
+ provider registry.terraform.io/hashicorp/external v2.3.5
+ provider registry.terraform.io/hashicorp/kubernetes v2.38.0
+ provider registry.terraform.io/hashicorp/random v3.8.1
```

### Affected Resource(s) or Data Source(s)

* `aws_s3_bucket_lifecycle_configuration`

### Expected Behavior

`terraform plan` is successful

### Actual Behavior

`terraform plan` errors with messages about Incompatible Types

This worked fine in 6.34.0, but started failing in 6.35.0

### Relevant Error/Panic Output

```console
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: Incompatible Types
│ 
│   with aws_s3_bucket_lifecycle_configuration.delete_certs_after_ninety_days,
│   on bucket.tf line 22, in resource "aws_s3_bucket_lifecycle_configuration" "delete_certs_after_ninety_days":
│   22: resource "aws_s3_bucket_lifecycle_configuration" "delete_certs_after_ninety_days" {
│ 
│ An unexpected error occurred while flattening configuration. This is always
│ an error in the provider. Please report the following to the provider
│ developer:
│ 
│ Source type
│ "*github.com/aws/aws-sdk-go-v2/service/s3/types.LifecycleRuleAndOperator"
│ cannot be flattened to target type
│ "github.com/hashicorp/terraform-provider-aws/internal/service/s3.lifecycleRuleAndOperatorModel".
╵
```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "6.35.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_s3_bucket" "example" {
  bucket = "example-lifecycle-and-filter-bug-12345"
}

resource "aws_s3_bucket_lifecycle_configuration" "example" {
  bucket = aws_s3_bucket.example.id

  rule {
    id = "expire_after_ninety_days"
    filter {
      and {
        prefix                   = "certs/"
        object_size_greater_than = 1
      }
    }
    status = "Enabled"
    expiration {
      days = 90
    }
  }
}

```
</details>

### Steps to Reproduce

```bash
terraform init
terraform plan
```

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

Regressed in 6.35.0

### Would you like to implement a fix?

No

### LINKED ISSUE #46774: 6.35. AgentCore Gateway Target: schema definition flatten error
### Terraform and AWS Provider Version

```console
Version 6.35
```

### Affected Resource(s) or Data Source(s)

Bedrock AgentCore Gateway Target

### Expected Behavior

Following schema was correct in prev. versions.

```
variable "tool_schema" {
  description = "Tool schema configuration for the gateway target"
  type = object({
    name        = string
    description = string
    input_schema = object({
      type        = string
      description = string
      properties = list(object({
        name        = string
        type        = string
        description = string
        required    = bool
      }))
    })
    output_schema = object({
      type        = string
      description = string
    })
  })
}
```

### Actual Behavior

```
Error: reading Bedrock AgentCore Gateway Target: Bedrock AgentCore Gateway Target: Bedrock AgentCore Gateway Target: Bedrock AgentCore Gateway Target: Unsupported Type

Cause: Cause: Cause: Cause: schema definition flatten: │ *types.SchemaDefinition
```

### Relevant Error/Panic Output

```console

```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl

```
</details>

### Steps to Reproduce

Upgrade to 6.35 and try to redeploy

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by YakDriver**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description

* **The bug:** PR #46741 changed AutoFlex to pass pointers to custom Flatteners, but existing Flatteners (like S3's 
`lifecycleRuleAndOperatorModel`) expected struct values. So when S3 tried `v.(awstypes.LifecycleRuleAndOperator)`, it failed because `v` was actually `*awstypes.LifecycleRuleAndOperator`.
* **The fix:** AutoFlex now always dereferences pointers before calling Flatteners. If the source is `*SomeStruct`, the Flattener receives `SomeStruct`. Nil pointers are handled earlier (target gets set to null), so Flatteners never need to worry about nil.
* **The regression test:** Added `TestFlattenFlattener_StructValue` which explicitly fails if a Flattener receives a pointer instead of a struct - this prevents the same mistake from happening again.

Example error:

```
Planning failed. Terraform encountered an error while generating this plan.

 Error: Incompatible Types
 
   with aws_s3_bucket_lifecycle_configuration.delete_certs_after_ninety_days,
   on bucket.tf line 22, in resource "aws_s3_bucket_lifecycle_configuration" "delete_certs_after_ninety_days":
   22: resource "aws_s3_bucket_lifecycle_configuration" "delete_certs_after_ninety_days" {
 
 An unexpected error occurred while flattening configuration. This is always
 an error in the provider. Please report the following to the provider
 developer:
 
 Source type
 "*github.com/aws/aws-sdk-go-v2/service/s3/types.LifecycleRuleAndOperator"
 cannot be flattened to target type
 "github.com/hashicorp/terraform-provider-aws/internal/service/s3.lifecycleRuleAndOperatorModel".

```

### Relations

Closes #46774.
Closes #46761.
Closes https://github.com/hashicorp/terraform-provider-aws/pull/46773.

### Output from Acceptance Testing

```console
% make t T=TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeRangeAndPrefix K=s3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-autoflex-regress-maybe 🌿...
TF_ACC=1 go1.25.7 test ./internal/service/s3/... -v -count 1 -parallel 20 -run='TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeRangeAndPrefix'  -timeout 360m -vet=off
2026/03/05 11:15:39 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/05 11:15:39 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeRangeAndPrefix
=== PAUSE TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeRangeAndPrefix
=== CONT  TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeRangeAndPrefix
--- PASS: TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeRangeAndPrefix (78.44s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3	85.507s
=== RUN   TestFlattenFlattener_StructValue
=== PAUSE TestFlattenFlattener_StructValue
=== CONT  TestFlattenFlattener_StructValue
=== RUN   TestFlattenFlattener_StructValue/Flattener_receives_struct_value,_not_pointer
=== PAUSE TestFlattenFlattener_StructValue/Flattener_receives_struct_value,_not_pointer
=== CONT  TestFlattenFlattener_StructValue/Flattener_receives_struct_value,_not_pointer
--- PASS: TestFlattenFlattener_StructValue (0.00s)
    --- PASS: TestFlattenFlattener_StructValue/Flattener_receives_struct_value,_not_pointer (0.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/framework/flex	0.389s
% go test ./internal/framework/flex/...
ok  	github.com/hashicorp/terraform-provider-aws/internal/framework/flex	(cached)
```

### CODE REVIEW

**Review by jar-b — APPROVED** [review]
LGTM 🚀

**Comment by ewbankkit** [comment]
Have we tested the `bedrockagentcore` regression case: https://github.com/hashicorp/terraform-provider-aws/issues/46774?

**Comment by YakDriver** [comment]
@ewbankkit In progress...

**Comment by YakDriver** [comment]
Should verify the regression is fixed for bedrock agent core:

```console
% make t T=TestAccBedrockAgentCoreGatewayTarget_ K=bedrockagentcore P=12     
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-autoflex-regress-maybe 🌿...
TF_ACC=1 go1.25.7 test ./internal/service/bedrockagentcore/... -v -count 1 -parallel 12 -run='TestAccBedrockAgentCoreGatewayTarget_'  -timeout 360m -vet=off
2026/03/05 12:51:04 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/05 12:51:04 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccBedrockAgentCoreGatewayTarget_basic
=== PAUSE TestAccBedrockAgentCoreGatewayTarget_basic
=== RUN   TestAccBedrockAgentCoreGatewayTarget_disappears
=== PAUSE TestAccBedrockAgentCoreGatewayTarget_disappears
=== RUN   TestAccBedrockAgentCoreGatewayTarget_targetConfiguration
=== PAUSE TestAccBedrockAgentCoreGatewayTarget_targetConfiguration
=== RUN   TestAccBedrockAgentCoreGatewayTarget_targetConfigurationMCPServer
=== PAUSE TestAccBedrockAgentCoreGatewayTarget_targetConfigurationMCPServer
=== RUN   TestAccBedrockAgentCoreGatewayTarget_credentialProvider
=== PAUSE TestAccBedrockAgentCoreGatewayTarget_credentialProvider
=== RUN   TestAccBedrockAgentCoreGatewayTarget_credentialProvider_invalid
=== PAUSE TestAccBedrockAgentCoreGatewayTarget_credentialProvider_invalid
=== RUN   TestAccBedrockAgentCoreGatewayTarget_metadataConfiguration
=== PAUSE TestAccBedrockAgentCoreGatewayTarget_metadataConfiguration
=== RUN   TestAccBedrockAgentCoreGatewayTarget_metadataConfiguration_invalidHeaders
=== PAUSE TestAccBedrockAgentCoreGatewayTarget_metadataConfiguration_invalidHeaders
=== CONT  TestAccBedrockAgentCoreGatewayTarget_basic
=== CONT  TestAccBedrockAgentCoreGatewayTarget_credentialProvider
=== CONT  TestAccBedrockAgentCoreGatewayTarget_targetConfiguration
=== CONT  TestAccBedrockAgentCoreGatewayTarget_targetConfigurationMCPServer
=== CONT  TestAccBedrockAgentCoreGatewayTarget_disappears
=== CONT  TestAccBedrockAgentCoreGatewayTarget_metadataConfiguration
=== CONT  TestAccBedrockAgentCoreGatewayTarget_metadataConfiguration_invalidHeaders
=== CONT  TestAccBedrockAgentCoreGatewayTarget_credentialProvider_invalid
--- PASS: TestAccBedrockAgentCoreGatewayTarget_credentialProvider_invalid (28.78s)
--- PASS: TestAccBedrockAgentCoreGatewayTarget_disappears (67.94s)
--- PASS: TestAccBedrockAgentCoreGatewayTarget_targetConfigurationMCPServer (79.01s)
--- PASS: TestAccBedrockAgentCoreGatewayTarget_metadataConfiguration_invalidHeaders (81.03s)
--- PASS: TestAccBedrockAgentCoreGatewayTarget_basic (83.14s)
--- PASS: TestAccBedrockAgentCoreGatewayTarget_metadataConfiguration (107.96s)
--- PASS: TestAccBedrockAgentCoreGatewayTarget_credentialProvider (144.64s)
--- PASS: TestAccBedrockAgentCoreGatewayTarget_targetConfiguration (170.24s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/bedrockagentcore	176.838s
```

**Comment by YakDriver** [comment]
@jar-b @ewbankkit Thank you!
