### ISSUE TITLE
aws_cloudfront_continuous_deployment_policy resource fails with "stagingDistributionDNSNamesModel does not implement attr.Value" error (regression in v6.17+)

### ISSUE THREAD

**Issue by chaya2z** [hashicorp/terraform-provider-aws#44951]
### Terraform and AWS Provider Version

```console
Terraform version: v1.13.3
AWS Provider version: 6.19.0
```

### Affected Resource(s) or Data Source(s)

* `aws_cloudfront_continuous_deployment_policy`

### Expected Behavior

The `aws_cloudfront_continuous_deployment_policy` resource should be created successfully without errors.

### Actual Behavior

Running `terraform apply` to create the `aws_cloudfront_continuous_deployment_policy` resource configuration fails with an error.

### Relevant Error/Panic Output

```console
╷
│ Error: Incompatible Types
│ 
│   with aws_cloudfront_continuous_deployment_policy.main,
│   on main.tf line 60, in resource "aws_cloudfront_continuous_deployment_policy" "main":
│   60: resource "aws_cloudfront_continuous_deployment_policy" "main" {
│ 
│ An unexpected error occurred while expanding configuration. This is always an error in the provider. Please report the following to the provider developer:
│ 
│ Source type "github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront.stagingDistributionDNSNamesModel" does not implement attr.Value
```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
terraform {
  required_version = "= 1.13.3"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "= 6.19.0"
      # version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "ap-northeast-1"
}

locals {
  origin_id = "example-origin"
}

data "aws_cloudfront_cache_policy" "caching_disabled" {
  name = "Managed-CachingDisabled"
}

resource "aws_cloudfront_distribution" "staging" {
  enabled = true
  staging = true

  default_cache_behavior {
    target_origin_id       = local.origin_id
    viewer_protocol_policy = "redirect-to-https"
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
    cache_policy_id        = data.aws_cloudfront_cache_policy.caching_disabled.id
  }

  origin {
    domain_name = "example.com"
    origin_id   = local.origin_id

    custom_origin_config {
      http_port              = 80
      https_port             = 443
      origin_protocol_policy = "https-only"
      origin_ssl_protocols   = ["TLSv1.2"]
    }
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }
}

resource "aws_cloudfront_continuous_deployment_policy" "main" {
  enabled = true

  staging_distribution_dns_names {
    items    = [aws_cloudfront_distribution.staging.domain_name]
    quantity = 1
  }

  traffic_config {
    type = "SingleWeight"

    single_weight_config {
      weight = 0
    }
  }
}

resource "aws_cloudfront_distribution" "primary" {
  enabled = true

  # NOTE: A continuous deployment policy cannot be associated to distribution
  # on creation. Set this argument once the resource exists.
  # continuous_deployment_policy_id = aws_cloudfront_continuous_deployment_policy.main.id

  default_cache_behavior {
    target_origin_id       = local.origin_id
    viewer_protocol_policy = "redirect-to-https"
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
    cache_policy_id        = data.aws_cloudfront_cache_policy.caching_disabled.id
  }

  origin {
    domain_name = "example.com"
    origin_id   = local.origin_id

    custom_origin_config {
      http_port              = 80
      https_port             = 443
      origin_protocol_policy = "https-only"
      origin_ssl_protocols   = ["TLSv1.2"]
    }
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }
}

```
</details>

### Steps to Reproduce

1. Apply the configuration.

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

Debug logs filtered to show only `aws_cloudfront_continuous_deployment_policy` resource related entries. CloudFront distribution creation and other unrelated logs are omitted for brevity.

```console
$  TF_LOG=DEBUG terraform apply
...
aws_cloudfront_continuous_deployment_policy.main: Creating...
2025-11-06T08:28:13.795+0900 [INFO]  Starting apply for aws_cloudfront_continuous_deployment_policy.main
2025-11-06T08:28:13.795+0900 [DEBUG] aws_cloudfront_continuous_deployment_policy.main: applying the planned Create change
2025-11-06T08:28:13.797+0900 [ERROR] provider.terraform-provider-aws_v6.19.0_x5: Source does not implement attr.Value: autoflex.source.path="" autoflex.target.type=string tf_req_id=3452588d-f268-07f6-0651-42ed91833982 tf_resource_type=aws_cloudfront_continuous_deployment_policy tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-provider-aws/internal/framework/flex/autoflex_expand.go:142 @module=aws.autoflex autoflex.source.type=github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront.stagingDistributionDNSNamesModel autoflex.target.path="" tf_mux_provider="*proto5server.Server" tf_provider_addr=registry.terraform.io/hashicorp/aws timestamp="2025-11-06T08:28:13.797+0900"
2025-11-06T08:28:13.797+0900 [ERROR] provider.terraform-provider-aws_v6.19.0_x5: Response contains error diagnostic: @module=sdk.proto diagnostic_severity=ERROR tf_proto_version=5.10 tf_provider_addr=registry.terraform.io/hashicorp/aws tf_rpc=ApplyResourceChange
  diagnostic_detail=
  | An unexpected error occurred while expanding configuration. This is always an error in the provider. Please report the following to the provider developer:
  | 
  | Source type "github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront.stagingDistributionDNSNamesModel" does not implement attr.Value
   diagnostic_summary="Incompatible Types" tf_req_id=3452588d-f268-07f6-0651-42ed91833982 tf_resource_type=aws_cloudfront_continuous_deployment_policy @caller=github.com/hashicorp/terraform-plugin-go@v0.29.0/tfprotov5/internal/diag/diagnostics.go:58 timestamp="2025-11-06T08:28:13.797+0900"
2025-11-06T08:28:13.799+0900 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2025-11-06T08:28:13.799+0900 [ERROR] vertex "aws_cloudfront_continuous_deployment_policy.main" error: Incompatible Types
2025-11-06T08:28:13.886+0900 [DEBUG] provider.terraform-provider-aws_v6.19.0_x5: HTTP Response Received: tf_provider_addr=registry.terraform.io/hashicorp/aws tf_req_id=0f26da83-02e0-6ab8-977f-5d19e6d9d09a tf_resource_type=aws_cloudfront_distribution tf_rpc=ApplyResourceChange http.duration=302 rpc.method=ListTagsForResource @caller=github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.67/logging/tf_logger.go:45 http.response.header.content_type=text/xml tf_aws.sdk=aws-sdk-go-v2 @module=aws aws.region=ap-northeast-1
  http.response.body=
  | <?xml version="1.0"?>
  | <Tags xmlns="http://cloudfront.amazonaws.com/doc/2020-05-31/"><Items/></Tags>
   http.response.header.x_amzn_requestid=025fba25-e154-42d8-8ced-7bb92fd6ec36 http.response_content_length=99 http.status_code=200 rpc.service=CloudFront tf_aws.signing_region="" http.response.header.date="Wed, 05 Nov 2025 23:28:13 GMT" rpc.system=aws-api tf_mux_provider="*schema.GRPCProviderServer" timestamp="2025-11-06T08:28:13.886+0900"
2025-11-06T08:28:13.892+0900 [WARN]  Provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected new value for aws_cloudfront_distribution.primary, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .web_acl_id: was null, but now cty.StringVal("")
      - .anycast_ip_list_id: was null, but now cty.StringVal("")
      - .default_root_object: was null, but now cty.StringVal("")
      - .viewer_certificate[0].iam_certificate_id: was null, but now cty.StringVal("")
      - .viewer_certificate[0].ssl_support_method: was null, but now cty.StringVal("")
      - .viewer_certificate[0].acm_certificate_arn: was null, but now cty.StringVal("")
      - .default_cache_behavior[0].origin_request_policy_id: was null, but now cty.StringVal("")
      - .default_cache_behavior[0].field_level_encryption_id: was null, but now cty.StringVal("")
      - .default_cache_behavior[0].smooth_streaming: was null, but now cty.False
      - .default_cache_behavior[0].realtime_log_config_arn: was null, but now cty.StringVal("")
      - .default_cache_behavior[0].response_headers_policy_id: was null, but now cty.StringVal("")
aws_cloudfront_distribution.primary: Creation complete after 2m59s [id=E2D83H7WGTP6TD]
2025-11-06T08:28:13.899+0900 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
╷
│ Error: Incompatible Types
│ 
│   with aws_cloudfront_continuous_deployment_policy.main,
│   on main.tf line 60, in resource "aws_cloudfront_continuous_deployment_policy" "main":
│   60: resource "aws_cloudfront_continuous_deployment_policy" "main" {
│ 
│ An unexpected error occurred while expanding configuration. This is always an error in the provider. Please report the following to the provider developer:
│ 
│ Source type "github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront.stagingDistributionDNSNamesModel" does not implement attr.Value
╵
2025-11-06T08:28:13.904+0900 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2025-11-06T08:28:13.920+0900 [INFO]  provider: plugin process exited: plugin=.terraform/providers/registry.terraform.io/hashicorp/aws/6.19.0/linux_amd64/terraform-provider-aws_v6.19.0_x5 id=180959
2025-11-06T08:28:13.920+0900 [DEBUG] provider: plugin exited
```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

* This appears to be a regression introduced in AWS Provider **v6.17**
* The same configuration works correctly with AWS Provider v5.100.0 and v6.16
* Related to PR https://github.com/hashicorp/terraform-provider-aws/pull/44861 which was included in v6.17

### Would you like to implement a fix?

No

**Comment by chaya2z** [comment]
**Update:** I've identified the exact version where this regression was introduced through testing.

**Tested versions:**

- :white_check_mark: v5.100.0: Works
- :white_check_mark: v6.16: Works  
- :x: v6.17: Fails
- :x: v6.19: Fails

(I haven't tested other versions between these, but the regression clearly appeared in v6.17)

The root cause is likely PR #44655. PR #44861 is also related to this issue.
