### ISSUE TITLE
[Bug]: Error emptying S3 Bucket when objects are in it, even though force-destroy is enabled.

### ISSUE THREAD

**Issue by porrige51122** [hashicorp/terraform-provider-aws#32307]
### Terraform Core Version

1.5.1

### AWS Provider Version

5.6.0, 5,6,1

### Affected Resource(s)

* aws_s3_bucket.bucket

### Expected Behavior

Terraform init an S3 bucket module which contains all the things to make an S3 bucket secure and with `force_destroy = true`

Terraform apply to an account.

Add objects to bucket.

Terraform destroy, empties the bucket and then destroys it and all corresponding resources.

### Actual Behavior

When running terraform destroy, it throws an error and doesn't delete the bucket or objects inside of it.

This is different to the behaviour in the version prior.

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: emptying S3 Bucket (test-bucket-...): listing S3 Bucket (test-bucket-...) object versions: InvalidArgument: Invalid attribute name specified.
│       status code: 400, request id: JD08VXT7P4Y19J58, host id: .../...
│ 
│ 
```

### Terraform Configuration Files

https://github.com/porrige51122/terraform-aws-secure-s3-bucket

### Steps to Reproduce

terraform init

terraform apply

add an object to the bucket

terraform destroy

### Debug Output

https://gist.github.com/porrige51122/b63e062cf5f670e84412c93d91830445

### Important Factoids

This is on an arm chip, and also failed on aws codebuild on an arm chip.

This also worked on versions <5.6.0

### Would you like to implement a fix?

No

**Comment by porrige51122** [comment]
I am going to see how minimal I can make the example. Hopefully that will narrow it down a bit more

**Comment by porrige51122** [comment]
Okay, I've removed all the extra infrastructure, and just deployed the s3 bucket resource alone and the error still occurs.

**Comment by ewbankkit** [comment]
Can reproduce with one of our unit tests:

```console
% AWS_REGION=us-west-2 go test -v ./internal/service/s3 -run=TestEmptyBucket -b ewbankkit-test-empty-bucket-001 -f
=== RUN   TestEmptyBucket
=== PAUSE TestEmptyBucket
=== CONT  TestEmptyBucket
    delete_test.go:33: error emptying S3 bucket (ewbankkit-test-empty-bucket-001): listing S3 Bucket (ewbankkit-test-empty-bucket-001) object versions: InvalidArgument: Invalid attribute name specified.
        	status code: 400, request id: YWJBA8NQBVRPCPMN, host id: fC3v2YQGsnRTjPsUh+g1WolqlDiyDBFrYSoASfAfaX7/tB+xVeLLlPye4YkqX8RdkpTdqwtNlfQWICS894j2yw==
--- FAIL: TestEmptyBucket (0.52s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/s3	6.342s
FAIL
```
